config:
  deploy_template: '.sqa/docker-compose-jepl.yaml'

sqa_criteria:
  QC.Sty:
    repos:
      hadolint tool:
        container: hadolint
        commands:
          - |
            #!/bin/bash
            hadolint */Dockerfile* --failure-threshold error
