config:
  credentials: []
  project_repos: {}
environment:
  JPL_DOCKERFORCEBUILD: enabled
sqa_criteria:
  QC.Sec:
    repos:
      this_repo:
        commands:
        - bandit -f json --quiet  --confidence-level high --severity-level high --recursive
          .
        container: docker-build
timeout: 5400
