config:
  credentials: []
  project_repos: {}
environment:
  JPL_DOCKERFORCEBUILD: enabled
sqa_criteria:
  QC.Sty:
    repos:
      this_repo:
        commands:
        - flake8 . --exclude docs/scipy-sphinx-theme
        container: docker-container
timeout: 5400
