config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
sqa_criteria:
  QC.Sec:
    repos:
      this_repo:
        commands:
        - bandit -f json --quiet  --confidence-level high --severity-level high --recursive
          .
        container: qc.sec_chummy-cyan-olm
timeout: 5400
